### ISSUE TITLE
Issue getting agent data using  PowerBI sample

### ISSUE THREAD

**Issue by taylojo** [WebexSamples/webex-contact-center-api-samples#261]
Trying to pull agent session data using the query below and just receive 'Nothing to export' when running the query from the webpage.   TIA

{
  # Agent Session "All Fields" example - Gets all the Agent Session fields - All fields in the ASR
  agentSession(from: 1719837745000 to: 1721220145000 ) {
    agentSessions {
      agentId
      userLoginId
      agentName
      agentSessionId
      state
      isActive
      startTime
      endTime
      teamId
      teamName
      siteId
      siteName
      
    }
  }
}

**Comment by jiwyatt** [comment]
Can you send me your .graphql file from the graphql directory?

**Comment by jiwyatt** [comment]
Please attach the file to github https://github.com/WebexSamples/webex-contact-center-api-samples/issues/261

The attachment was not received.

**Comment by taylojo** [comment]
OK,. had to zip first ,.
[TestAgentSessionFields.graphql.zip](https://github.com/user-attachments/files/16285644/TestAgentSessionFields.graphql.zip)

**Comment by jiwyatt** [comment]
Thanks for the file.

[Issue]
The current version of the code for reporting-samples/graphql-powerbi-sample was written prior to the agentSession query.

[Solution]
The code needs to be updated to support the agentSession query.

[Action Item]
I will modify the code to include the new query. 
and/or
Feel free to modify the code as you see fit. 

[Summary]
We have identified that the current version of our example code in the reporting-samples/graphql-powerbi-sample repository does not include support for the 'agentSession' query, which is a recent addition. To address this, we are taking action to update the codebase to integrate this query. We encourage you to also feel free to make any adjustments to the code that you see fit for your purposes. Once the update is complete, it will reflect the agentSession query, allowing for seamless integration and enhanced reporting functionality. 

Thank you for your patience as we make these improvements.

**Comment by taylojo** [comment]
Thanks for the support!

**Comment by jiwyatt** [comment]
agentSession search is now supported.

example search string is located in the directory:
   graphql-powerbi-sample/graphql/agentSession.graphql

**Comment by taylojo** [comment]
Thanks for the update,.  tested and still seeing "nothing to export' .  

 Notice the following error in the Java app  

 WARN  c.w.a.d.service.SearchGraphQLService.doSearch - NullPointerException
java.lang.NullPointerException: Cannot invoke "com.webexcc.api.demo.model.TaskDetails.getTasks()" because the return value of "com.webexcc.api.demo.model.Data.getTaskDetails()" is null
